# Generated by Django 3.0.4 on 2020-03-17 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_auto_20200317_0840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='torrents',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='movies.Torrent'),
        ),
    ]
