# Generated by Django 3.0.4 on 2020-03-17 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_auto_20200317_0917'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='torrents',
        ),
        migrations.AddField(
            model_name='movie',
            name='torrents',
            field=models.ManyToManyField(to='movies.Torrent'),
        ),
    ]
